import dotenv from 'dotenv';

dotenv.config();

export const ENV = {
    PORT: process.env.PORT,
    MONGODB_URL: process.env.MONGODB_URL,
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
    ACCESS_KEY_SECRET: process.env.ACCESS_KEY_SECRET,
    REFRESH_KEY_SECRET: process.env.REFRESH_KEY_SECRET,
    PINECONE_SECRET_KEY: process.env.PINECONE_SECRET_KEY,
    API_KEY_GENERATION_SECRERT_KEY: process.env.API_KEY_GENERATION_SECRERT_KEY,
    GOOGLE_EMAIL_USER: process.env.GOOGLE_EMAIL_USER,
    GOOGLE_APP_PASSWORD: process.env.GOOGLE_APP_PASSWORD,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    STRIPE_PUBLIC_KEY: process.env.STRIPE_PUBLIC_KEY,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    CLIENT_URL: process.env.CLIENT_URL,
    ALLOWED_ORIGINS: process.env.ALLOWED_ORIGINS,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    PINECONE_API_KEY: process.env.PINECONE_API_KEY,
    FASTROUTER_API_KEY: process.env.FASTROUTER_API_KEY,
    FASTROUTER_BASE_URL: process.env.FASTROUTER_BASE_URL,
    SERVICE_API_SECRET: process.env.SERVICE_API_SECRET,

        // OpenAI
    FASTROUTER_OPENAI_MODEL_1: process.env.FASTROUTER_OPENAI_MODEL_1,
    FASTROUTER_OPENAI_MODEL_2: process.env.FASTROUTER_OPENAI_MODEL_2,
    FASTROUTER_OPENAI_MODEL_3: process.env.FASTROUTER_OPENAI_MODEL_3,
    FASTROUTER_OPENAI_MODEL_4: process.env.FASTROUTER_OPENAI_MODEL_4,

    // Anthropic
    FASTROUTER_ANTHROPIC_MODEL_1: process.env.FASTROUTER_ANTHROPIC_MODEL_1,
    FASTROUTER_ANTHROPIC_MODEL_2: process.env.FASTROUTER_ANTHROPIC_MODEL_2,
    FASTROUTER_ANTHROPIC_MODEL_3: process.env.FASTROUTER_ANTHROPIC_MODEL_3,
    FASTROUTER_ANTHROPIC_MODEL_4: process.env.FASTROUTER_ANTHROPIC_MODEL_4,

    // Gemini
    FASTROUTER_GEMINI_MODEL_1: process.env.FASTROUTER_GEMINI_MODEL_1,
    FASTROUTER_GEMINI_MODEL_2: process.env.FASTROUTER_GEMINI_MODEL_2,

    // Perplexity
    FASTROUTER_PERPLEXITY_MODEL_1: process.env.FASTROUTER_PERPLEXITY_MODEL_1,
    FASTROUTER_PERPLEXITY_MODEL_2: process.env.FASTROUTER_PERPLEXITY_MODEL_2,
    FASTROUTER_PERPLEXITY_MODEL_3: process.env.FASTROUTER_PERPLEXITY_MODEL_3,

    // Grok (xAI)
    FASTROUTER_GROK_MODEL_1: process.env.FASTROUTER_GROK_MODEL_1,
    FASTROUTER_GROK_MODEL_2: process.env.FASTROUTER_GROK_MODEL_2,

    // DeepSeek
    FASTROUTER_DEEPSEEK_MODEL_1: process.env.FASTROUTER_DEEPSEEK_MODEL_1,
    FASTROUTER_DEEPSEEK_MODEL_2: process.env.FASTROUTER_DEEPSEEK_MODEL_2,

    // GLM (Z-AI)
    FASTROUTER_GLM_MODEL_1: process.env.FASTROUTER_GLM_MODEL_1,
    FASTROUTER_GLM_MODEL_2: process.env.FASTROUTER_GLM_MODEL_2,

    NODE_ENV: process.env.NODE_ENV,
    PYTHON_BACKEND_URL: process.env.PYTHON_BACKEND_URL,
}