import dotenv from 'dotenv';

dotenv.config();

export const ENV ={
    PORT: process.env.PORT,
    MONGODB_URL: process.env.MONGODB_URL, 
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
    ACCESS_KEY_SECRET: process.env.ACCESS_KEY_SECRET,
    REFRESH_KEY_SECRET: process.env.REFRESH_KEY_SECRET,
    GOOGLE_EMAIL_USER: process.env.GOOGLE_EMAIL_USER,
    GOOGLE_APP_PASSWORD: process.env.GOOGLE_APP_PASSWORD,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    STRIPE_PUBLIC_KEY: process.env.STRIPE_PUBLIC_KEY,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    CLIENT_URL: process.env.CLIENT_URL,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    PINECONE_SECRET_KEY: process.env.PINECONE_SECRET_KEY,
    PINECONE_API_KEY: process.env.PINECONE_API_KEY,
    FASTROUTER_API_KEY: process.env.FASTROUTER_API_KEY,
    FASTROUTER_BASE_URL: process.env.FASTROUTER_BASE_URL,
    FASTROUTER_OPENAI_MODEL_1: process.env.FASTROUTER_OPENAI_MODEL_1,
    FASTROUTER_OPENAI_MODEL_2: process.env.FASTROUTER_OPENAI_MODEL_2,
    FASTROUTER_ANTHROPIC_MODEL_1: process.env.FASTROUTER_ANTHROPIC_MODEL_1,
    FASTROUTER_ANTHROPIC_MODEL_2: process.env.FASTROUTER_ANTHROPIC_MODEL_2,
    FASTROUTER_GEMINI_MODEL_1: process.env.FASTROUTER_GEMINI_MODEL_1,
    FASTROUTER_GEMINI_MODEL_2: process.env.FASTROUTER_GEMINI_MODEL_2,
    FASTROUTER_GROK_MODEL_1: process.env.FASTROUTER_GROK_MODEL_1,
    FASTROUTER_DEEPSEEK_MODEL_1: process.env.FASTROUTER_DEEPSEEK_MODEL_1,
    NODE_ENV: process.env.NODE_ENV,
    PYTHON_BACKEND_URL: process.env.PYTHON_BACKEND_URL,
}