export const PLAN_CONFIG = {
  free: {
    price: 0,
    chatbotLimit: 1,
    apiLimit: 0,
    questionLimit: 30,
    vectorStore: "chroma",
    support: "community",
    watermark: "powered-by-krira",
    analytics: false,
    earlyAccess: false,
  },
  pro_monthly: {
    price: 35,
    chatbotLimit: 3,
    apiLimit: 5000,
    questionLimit: 5000,
    vectorStore: "pinecone",
    support: "priority-email",
    watermark: "custom",
    analytics: true,
  },
  enterprise_monthly: {
    price: 135,
    chatbotLimit: 8,
    apiLimit: 40000,
    questionLimit: 40000,
    vectorStore: "pinecone",
    support: "priority-24x7",
    watermark: "custom",
    analytics: true,
    earlyAccess: true,
    teamMembers: 5,
  },
  annual_startup: {
    price: 1365,
    chatbotLimit: 8,
    apiLimit: 40000,
    questionLimit: 40000,
    vectorStore: "pinecone",
    support: "priority-24x7",
    watermark: "custom",
    analytics: true,
    earlyAccess: true,
    teamMembers: 5,
    billingCycle: "annual",
  },
};
